### PR TITLE
fix: Add utf8 charset support to return value

### PR DESCRIPTION
**Pull request by dpylr**
I fix this problem by modify the DEFAULT_REPRESENTATIONS and default_mediatype in init.py
it works fine, but many tests failed! But i don't know how to fix the errors ! 
So I hope this could in some way ! 
Thanks So Much!

dpylr@bacc2ee

### CODE REVIEW

**Comment by freddrake** [comment]
``application/json`` does not have a ``charset`` parameter:
https://tools.ietf.org/html/rfc7159#section-11

**Comment by joshfriend** [comment]
The important bit from the link @freddrake posted:

> Note:  No "charset" parameter is defined for this registration.  Adding one really has no effect on **compliant recipients**.

(emphasis mine)

**Comment by dpylr** [comment]
Thanks very much @joshfriend  and @freddrake  !
I completely agree with RFC .
but i notice that  make_response in flask_restfule.__init__.py 
https://github.com/flask-restful/flask-restful/blob/master/flask_restful/__init__.py#L512
before this line **L512**
resp.headers['Content-Type']  is **text/html; charset=utf-8** , with charset
but **L512** set Content-Type to **application/json**, and lost charset utf-8
then cause the return value problem.
should we also keep the charset from **L511** ?
If we do so , 'No "charset" parameter is defined for this registration' and we solve the problem.
what's your opinion?

**Comment by freddrake** [comment]
I'm not sure what you're asserting is lost.

If the response is application/json, the body will be encoded in UTF-8 and the Content-Type header will specify application/json.  Are you asserting the response should explicitly identify the UTF-8 encoding even though it's specified as part of Content-Type: application/json?

**Comment by joshfriend** [comment]
@dpylr `charset=utf-8` appears nowhere in the code. Like others have said, charset is always utf-8 for a content type of `application/json`, so it's not possible to loose that information, unless your client is not conforming to the RFC specs.

**Pull request closed without merging**
