### PR TITLE
fix: wrong import upstream changes

### PR DESCRIPTION
**Pull request by dendisuhubdy**
Change `helpers` to `scaffold` from upstream changes here https://github.com/pallets/flask/blob/2f0c62f5e6e290843f03c1fa70817c7a3c7fd661/src/flask/scaffold.py

Closes https://github.com/flask-restful/flask-restful/issues/912

### CODE REVIEW

**Comment by Anupam02** [comment]
Hi , Just wanted to check if this PR would be merged soon, or there is any other alternative , other than going to previous version.

I got redirected here from - https://github.com/pallets/flask/issues/4009
its not working since flask upgrade has happened.

Thanks in advance.

**Comment by joshfriend** [comment]
@Anupam02 please see the comment directly above yours

**Comment by belmarca** [comment]
@joshfriend The method is not really private and has an assertion. The alternative is to just copy the code inside `__init__.py` as

```
        if endpoint is None:
                assert view_func is not None, "expected view func if endpoint is not provided."
                endpoint = view_func.__name__
```

I'm not sure what's to gain either way. The fix works for us, we'll keep it such until resolved.

**Comment by joshfriend** [comment]
@belmarca The method _is private_. The Flask issue you came from says so explicitly, and you can also infer this from the `_` prefix on the method. You will also not find any docs for it [here](https://flask.palletsprojects.com/en/2.0.x/), nor will you see this change in the CHANGELOG.

Also, you would not need the assertion as the `view_func` will never be `None` here. Just replace the use of the private function with the equivalent: `view_func.__name__` and I will merge that.

**Comment by belmarca** [comment]
What I meant is that even thought the method is hinted to be private, it's not in a strict sense. Anyway, this is not my PR. Ping @dendisuhubdy to change this.

**Review by rena2damas — CHANGES_REQUESTED** [review]
This is not compatible with Flask<2.0.0. Needs a ```try/except``` for that effect.

**Comment by rena2damas** [comment]
> This is not compatible with `Flask<2.0.0`. Needs a `try/except` for that effect.

Or you just roll the change together with bumping ```Flask``` version

**Comment by rena2damas** [comment]
So what's missing to merge and close this issue? The current version is breaking the projects to a lot of us.

**Comment by rena2damas** [comment]
Because desperate times call for desperate measures, here is a monkey patch I am not proud of, but gets the job done while the merge is not in place:

```python
import flask.scaffold
flask.helpers._endpoint_from_view_func = flask.scaffold._endpoint_from_view_func
from flask_restful import Api
...
```

**Comment by joshfriend** [comment]
fixed in #915

**Comment by flutterq** [comment]
[[Solved] cannot import name ‘_endpoint_from_view_func’ from ‘flask.helpers’ in python](https://exerror.com/solved-cannot-import-name-_endpoint_from_view_func-from-flask-helpers-in-python/)

**Comment by yiqingzhang** [comment]
```
Flask-RESTful==0.3.9
```
This Flask-RESTful version solves the issue for me.

**Comment by developython14** [comment]
> Change `helpers` to `scaffold` from upstream changes here https://github.com/pallets/flask/blob/2f0c62f5e6e290843f03c1fa70817c7a3c7fd661/src/flask/scaffold.py
> 
> Closes #912

@dendisuhubdy   thank you  very  much  but how you was think that the erros was in path of packages !!!

**Pull request closed without merging**
