### PR TITLE
Fixed a regression introduced by Flask 1.0

### PR DESCRIPTION
**Pull request by frol**
Here is the related issue: https://github.com/mitsuhiko/flask/issues/1477

### CODE REVIEW

**Comment by joshfriend** [comment]
Read the discussion and changes a bit more closely. The `view_functions` attribute was removed from the `Blueprint` class, **not** the `Flask` class. `Flask.view_functions` is [still there.](https://github.com/mitsuhiko/flask/blob/7f3867491570746a4c14bdaa5bd59ec1b64cbfea/flask/app.py#L369)

**Comment by frol** [comment]
@joshfriend WAT?! I'm surprised that the owner of flask-restful project doesn't know about Blueprint-style usage: http://flask-restful.readthedocs.org/en/latest/intermediate-usage.html?highlight=blueprint#use-with-blueprints

**Comment by joshfriend** [comment]
Sorry, It was late and I just forgot :)

**Comment by frol** [comment]
Thank you! :)

**Pull request merged**
