### PR TITLE
Do not consider 'null' as a valid value for a required field.

### PR DESCRIPTION
**Pull request by rishi-freshbooks**

### CODE REVIEW

**Comment by joshfriend** [comment]
My thinking is that since `null` and "not present" are two distinctly different things, they should not be treated the same. I think it would be better to add a separate flag (e.g. `nullable=True`) that would control this new behavior. As is, this is likely to break things for other users in unexpected ways.

**Comment by jbouzekri** [comment]
@joshfriend I am very interested in this feature in order to allow or disallow the nullable on field not required.

**Comment by joshfriend** [comment]
@jbouzekri try this:

```python
def non_null(value):
    if value is None:
        raise ValueError('Must not be null')
    return value

parser.add_argument('example', type=non_null, required=True)
```

Ideally, you would replace this with the following (if the feature was implemented how my other comment described):

```python
parser.add_argument('example', required=True, nullable=False)
```

**Comment by jbouzekri** [comment]
@joshfriend : yeah it is a fallback solution but it means that I cannot have an input filter for string or other type. 

The idea was : a field not required, but if present it should not be null but MUST be a datetime for example.

With the second solution, it could allow to remove the parameter from the dict built by the request parser.

**Comment by jbouzekri** [comment]
@joshfriend : I have tested your fallback but it is not working.

I think because of this line : https://github.com/flask-restful/flask-restful/blob/master/flask_restful/reqparse.py#L109

**Comment by joshfriend** [comment]
Hmmm, yeah that might be an issue. Wouldn't replacing it with the following work?

```python
if value is None:
    if self.nullable:
        return None
    else:
        raise ValueError('Must not be null!')
```

**Comment by jbouzekri** [comment]
After having added nullable=True to the constructor, it works like a charm.

Would you consider to add this code and release a new version soon ?

**Comment by jbouzekri** [comment]
@joshfriend : Hi sorry to bug you again with this but I think it is a very important feature. Will you be able to merge it soon and release a new version ? Thanks in advance.

**Comment by joshfriend** [comment]
fixed by #538

**Pull request closed without merging**
