### PR TITLE
Add multiple arguments from dict or file, PEP8 cleanup

### PR DESCRIPTION
**Pull request by Ashafix**
* Multiple `reqparser` arguments can be added by supplying either a `dict` or filename
* `Argument` now has a `__repr__` and `__str__` function
* Added test cases for all new functionality
* Clean-up of some minor PEP8 violations

### CODE REVIEW

**Comment by Ashafix** [comment]
Accidentally rebased the commit of @ng95junwei with mine. Had some issues to get everything working with Python 2.6 but it should be fine now.

**Comment by Ashafix** [comment]
Just saw that Python 2.6 support was removed which means I could get rid of the ugly compatibility `try/catch` blocks.

**Comment by joshfriend** [comment]
Thanks for the proposal, it's a very interesting feature and the inclusion of test cases is awesome!

I've decided not to merge it though. I think this is something that would work well as a standalone package. Generating request parsers from yaml files isn't something that I think most flask-restful users would use and I'd like to keep `reqparse` on the slim side feature-wise. Also, the inclusion of the `pyyaml` dependency is not ideal for the common user.

If this were a more common use case that was included in flask-restful, I would want to see it packaged as an [optional feature](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) so that you only pull in the added dependencies if you specifically request to use the feature.

Finally, if you were to make a separate PR with just the pep8 cleanups, I would be glad to merge that in. I just didn't see a way to cherry-pick just those changes out of this PR.

**Comment by Ashafix** [comment]
@joshfriend Thanks for taking the time to comment. The PEP8 changes are now in a separate pull request (#769)

I'll check how can I add the yaml to reqparse option.

I agree that having the pyyaml depedency is unnecessary for most users. Having the ability to create the reqparser from a dict allows better separation of code and content in my opinion. Perhaps just add the `add_arguments` function without the option of using yaml files, just a `dict` to `reqparser` converter?

**Pull request closed without merging**
