### PR TITLE
Fix truncation of microseconds in iso8601 datetime output (fixes #368)

### LINKED ISSUE #368: DateTime marshaller truncates fractional seconds
The `flask_restful.inputs.iso8601()` utility method is truncating fractional seconds, which makes the marshalling of date-times loosing fractional precision.

I don't see a rationale for removing milli/microseconds as this level of precision is supported by ISO 8601 and Python.

### PR DESCRIPTION
**Pull request by joshfriend**
Uses the `isoformat()` method built into the `datetime` class to perform the 8601 serialization instead of the funky `timetuple` nonsense.

Also fixes the issue of forcing conversion to UTC on output.

Basically the other half of #381

### CODE REVIEW

**Comment by skimbrel** [comment]
+1

**Comment by joshfriend** [comment]
@skimbrel the only downside I can think of here is that the output format [varies](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat) if microseconds/timezone are nonzero. Libraries such as GSON (android/java JSON parser) or anyone using a `strptime` parser might not understand the format correctly after this change.

**Comment by skimbrel** [comment]
Oof, right. I'd say it might be worth saving for 1.0 but I don't know whether marshal will even be around then...

**Comment by joshfriend** [comment]
The ISO8601 marshalling was added very recently (#345) so it's probably safe to fix?

**Comment by skimbrel** [comment]
Aight, go for it.

**Pull request merged**
