### PR TITLE
allow/disallow null value in argument

### PR DESCRIPTION
**Pull request by jbouzekri**
Hi,

As we discussed in #498, I have made a pull request with these changes.

Please consider merging it soon and releasing a new version. I am unable to release my project in production without it and I would like to avoid making a reference to my fork. 

Thanks once again for your support on this.

Regards

### CODE REVIEW

**Comment by joshfriend** [comment]
Thanks for the patch! The soonest I can get to making a new release would be Monday as I am stuck with dialup internet where I'm staying for the holiday weekend.

**Comment by jbouzekri** [comment]
No problem. Monday is perfect as I am on weekend myself. Cheers.

**Comment by jbouzekri** [comment]
@joshfriend : Hi, sorry to bug you again with this. But could you make the new release ? :) Thanks in advance

**Comment by jbouzekri** [comment]
@joshfriend : Hi, this @jbouzekri again :) A little up to remind you of my need for this new release. Pretty please :)

**Comment by joshfriend** [comment]
@jbouzekri Thanks for your patience, I was unexpectedly busy last week.

See #546.

**Comment by jbouzekri** [comment]
Thx !!!!!!

**Pull request merged**
